### ISSUE TITLE
No update since 2017-09-21

### ISSUE THREAD

**Issue by TibboddiT** [ryotarai/github_trends_rss#10]
It seems the rss stopped working few days ago :(

Your code still work, I tested it locally.

**Comment by khakulov** [comment]
@ryotarai any plans to fix this?

**Comment by stormmwa** [comment]
Nothing fancy, but have it running at:
http://stormauction.s3-website-us-west-2.amazonaws.com/github_trends.html

**Comment by Daniel-at-github** [comment]
Thanks @stormmwa !

**Comment by dfct** [comment]
Agreed, thank you @stormmwa!

**Comment by khakulov** [comment]
Thank you @stormmwa!

**Comment by Fgruntjes** [comment]
Many thanks to you @stormmwa

**Comment by tarr1124** [comment]
It doesn't seem to work @stormmwa

**Comment by stormmwa** [comment]
@tarr1124 updating on the hour, what seems to be not working?

**Comment by tarr1124** [comment]
@stormmwa It just works. Thanks 😃
