### ISSUE TITLE
Rss now are 0 byte size

### ISSUE THREAD

**Issue by Daniel-at-github** [ryotarai/github_trends_rss#7]
Hi, your project is very useful.

Seems that it is'nt working now, all rss came with 0 bytes to me.
Example:
~~~ bash
$ curl http://github-trends.ryotarai.info/rss/github_trends_all_monthly.rss 2>/dev/null | wc --bytes
0
~~~

The latest rss entry that I have retrieved is from 2016-11-01T13:27:47+0100

**Comment by Daniel-at-github** [comment]
Hi @ryotarai, seems that broken rss is solved in #6 PR

**Comment by ryotarai** [comment]
I'm sorry. I am going to work on this tonight.

**Comment by Daniel-at-github** [comment]
You don't have to be sorry, we have to be grateful.
You have 145 repositories and you fixed and ported this to Python overnight...

Thanks a lot for your work :smile:

**Comment by Daniel-at-github** [comment]
Hi,
It seems done, but now Weekly and Monthly have no entries:

``` bash
for LANG in all python r pascal jupyter-notebook java lua powershell
do
  for PERIOD in daily weekly monthly
  do
    URL="http://github-trends.ryotarai.info/rss/github_trends_${LANG}_${PERIOD}.rss"
    # echo curl "$URL"
    SIZE=$(curl "$URL" 2>/dev/null | wc --bytes --)
    echo "$LANG $PERIOD $SIZE"
  done
done
```

(570 and 573 bytes are rss skeleton with no entries)

```
all daily 6883
all weekly 570
all monthly 573
python daily 6790
python weekly 559
python monthly 562
r daily 6637
r weekly 544
r monthly 547
pascal daily 6643
pascal weekly 559
pascal monthly 562
jupyter-notebook daily 8188
jupyter-notebook weekly 589
jupyter-notebook monthly 592
java daily 7374
java weekly 553
java monthly 556
lua daily 6585
lua weekly 550
lua monthly 553
powershell daily 6755
powershell weekly 571
powershell monthly 574
```

I'm trying now (2016-11-19T05:57:09+0000) accessing to https://github.com/trending/python?since=monthly and it shows this message:

> **Trending repositories results are currently being dissected.**
> 
> This may be a few minutes. Now would be a great time to write that novel you’ve always been talking about. 

No `repo-list` string appears in source code, I think that this line of code:

https://github.com/ryotarai/github_trends_rss/blob/master/lambda/functions/worker/main.py#L22

``` python
lis = tree.cssselect("ol.repo-list li")
```

will fail or get None.

May be this is it, and the program have to retry time later (or choose other time window to start).

**Comment by Rarst** [comment]
Weekly and monthly trends had been broken on Github side, I've whined on twitter while back and they seemed to have fixed it now.

**Comment by Daniel-at-github** [comment]
Thanks for make the fix happen :smile:
